In [3]:
# Homework 3
# Design a decision tree 
# Visualize your tree using pydot. 
# Try different depths and inpurity criteria (Gini and Information Gain). 
# Compare with KNN 

from sklearn.datasets import load_iris
from sklearn import tree

from IPython.display 

#Importing Packages

import Image  
import pydotplus 


In [ ]:
def tree_with_gini(iris_data, iris_target, depth):
    
    classifier = tree.DecisionTreeClassifier(max_depth=depth) 
    # The maximum depth of the tree. 
    # If None, then nodes are expanded until all leaves are pure 
    # or until all leaves contain less than min_samples_split samples.
    
    
    classifier = classifier.fit(iris_data, iris_target)
    # Build a decision tree classifier from the training set (iris_data, iris_target).
    
    return classifier;

In [9]:
# Iris Dataset loading phase

from sklearn import datasets
iris = datasets.load_iris()

print(iris.data) 

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [13]:
# Import required packages

from sklearn.model_selection import LeaveOneOut
import numpy as np

from sklearn import neighbors


In [ ]:
# Try Leave-One-Out method

# Each learning set is created by taking all the samples except one, the test set being the sample left out.
# Thus, for n samples, we have n different training sets and n different tests set. 

for check_depth_of_data in range(1,20):
    
    LeaveOneOut_Test = LeaveOneOut()
    Sum_of_Total = 0
    Gini_Result = 0
    Entropy_Result = 0
    KNN_Result = 0
    
    for train, test in LeaveOneOut_Test.split(iris.data):
        Sum_of_Total = Sum_of_Total + 1

        testData = list()
        
        testTarget = list()
        
        for i in train:
            testData.append(iris.data[i])
            testTarget.append(iris.target[i])
        
        # First classifier will be tested for decision tree with Gini
        # Gini index - a criterion to minimize the probability of misclassification
        classifier = tree_with_gini(testData, testTarget, check_depth_of_data)
        
        if classifier.predict(iris.data[test]) == iris.target[test]:
            Gini_Result = Gini_Result + 1
        
        
        # Second classifier will be tested for decision tree with Entropy
        # Entropy - a way to measure impurity
        classifier2 = create_tree_using_entropy(testData, testTarget, check_depth_of_data)
        
        # Predict the class labels for the provided data for Entropy
        if classifier2.predict(iris.data[test]) == iris.target[test]:
            Entropy_Result = Entropy_Result + 1
        
        
        # Third classifier will be for KNN algorithm
        classifier3 = neighbors.KNeighborsClassifier(1, weights='uniform') 
        # Classifier implementing the k-nearest neighbors vote
        # uniform weighting: All points in each neighborhood are weighted equally.
        
        classifier3.fit(testData, testTarget)
        
        if classifier3.predict(iris.data[test]) == iris.target[test]:
            KNN_Result = KNN_Result + 1
            
    # Print the results of the methods  
    
    # GINI results with max Depth and percentage
    print "Depth of Decision Tree " + str(check_depth_of_data) + " GINI Result:   %" + str(Gini_Result*100/Sum_of_Total)

    # Entropy results with max Depth and percentage
    print "Depth of Decision Tree " + str(check_depth_of_data) + " Entropy Result: %" + str(Entropy_Result*100/Sum_of_Total)

    # KNN results with max Depth and percentage
    print "Result of KNN method is %" + str(KNN_Result*100/Sum_of_Total
 
                                                                                       
                                            
# For KNN:
# KNN determines neighborhoods, so there must be a distance metric. 
# This implies that all features must be numeric. 
# Distance metrics may be effected by varying scales between attributes and also high-dimensional space.
                                            
# For Decision Tree:
# Decision Tree predicts a class for a given input vector. The attributes may be numeric or nominal.

#COMMENT: 
# If you would like to find similar examples you could use K-NN. 
# If you want to classify examples you could use Decision Tree.                                          
                                 
                                            
                                            
# The Results of the program will be as the following:
                                            
# Results show that as the depth of the tree maximizes, the accuracy increases 
# With this dataset the final results are closer to each other 
                            
                                            
                                            
#  Depth of Decision Tree 1 GINI Result:   %33
#  Depth of Decision Tree 1 Entropy Result: %33

#  Depth of Decision Tree 2 GINI Result:   %95
#  Depth of Decision Tree 2 Entropy Result: %95

#  Depth of Decision Tree 3 GINI Result:   %94
#  Depth of Decision Tree 3 Entropy Result: %95

#  Depth of Decision Tree 4 GINI Result:   %94
#  Depth of Decision Tree 4 Entropy Result: %94

#  Depth of Decision Tree 5 GINI Result:   %94
#  Depth of Decision Tree 5 Entropy Result: %94

#  Depth of Decision Tree 6 GINI Result:   %95
#  Depth of Decision Tree 6 Entropy Result: %94

#  Depth of Decision Tree 7 GINI Result:   %95
#  Depth of Decision Tree 7 Entropy Result: %94

#  Depth of Decision Tree 8 GINI Result:   %94
#  Depth of Decision Tree 8 Entropy Result: %94

#  Depth of Decision Tree 9 GINI Result:   %94
#  Depth of Decision Tree 9 Entropy Result: %95

#  Depth of Decision Tree 10 GINI Result:   %94
#  Depth of Decision Tree 10 Entropy Result: %95

#  Depth of Decision Tree 11 GINI Result:   %95
#  Depth of Decision Tree 11 Entropy Result: %94

#  Depth of Decision Tree 12 GINI Result:   %94
#  Depth of Decision Tree 12 Entropy Result: %95

#  Depth of Decision Tree 13 GINI Result:   %95
#  Depth of Decision Tree 13 Entropy Result: %95

#  Depth of Decision Tree 14 GINI Result:   %94
#  Depth of Decision Tree 14 Entropy Result: %94

#  Depth of Decision Tree 15 GINI Result:   %94
#  Depth of Decision Tree 15 Entropy Result: %94

#  Depth of Decision Tree 16 GINI Result:   %94
#  Depth of Decision Tree 16 Entropy Result: %95

#  Depth of Decision Tree 17 GINI Result:   %96
#  Depth of Decision Tree 17 Entropy Result: %94

#  Depth of Decision Tree 18 GINI Result:   %95
#  Depth of Decision Tree 18 Entropy Result: %94

#  Depth of Decision Tree 19 GINI Result:   %96
#  Depth of Decision Tree 19 Entropy Result: %96

#  Result of KNN method is  %96                             
                            
